application:
  name: "RealTimeKPIProcessing"

input:
  kafka:
    bootstrap_servers: "kafka-server:9092"
    topics: ["transactions"]
    group_id: "kpi_processing_group"

kpis:
  - name: "Total Transaction Amount Per Minute"
    source: "transactions"
    transformations:
      - type: "window"
        duration: "1 minute"
      - type: "sum"
        field: "amount"

  - name: "Active Customers Per Minute"
    source: "transactions"
    transformations:
      - type: "window"
        duration: "1 minute"
      - type: "distinct_count"
        field: "customer_id"

  - name: "Abnormal Transactions Per Minute"
    source: "transactions"
    transformations:
      - type: "filter"
        criteria: "amount > 10000"
      - type: "window"
        duration: "1 minute"
      - type: "count"

output:
  kafka:
    bootstrap_servers: "kafka-server:9092"
    topic: "kpi_metrics"
